name: "Pull Request"
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
env:
  GO_VERSION: 1.21 # Updated to a valid Go version
jobs:
  lint-test:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "Install Dependencies"
        run: go mod tidy

      - name: "Golang CI Lint"
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: "Run Tests"
        run: go test -v ./...